### ISSUE TITLE
Timings Plugin Very High

### ISSUE THREAD

**Issue by thinh2118** [Tobias-2006/AutoPickup#4]
Plugin: AutoPickup v1.0.2 Event: tobias14\autopickup\AutoPickup::onBreak(BlockBreakEvent) Time: 1566949368 Count: 356 Avg: 4401543 Violations: 28
This will be lag server? how to fix lag plugin.

**Comment by tobiaskirchmaier** [comment]
I don't know anything about this plugin causing lags...
I just use an event like everyone else does.
